
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-api-deployment # the deplpoyment name on clusrter
  namespace: default
  labels:
    app: redis-api-deployment
spec:
  selector:
    matchLabels:
      app: redis-api-pod # the pod name that will contain container
  template: # confoguration for deployment
    metadata:
      labels:
        app: redis-api-pod
    spec:
      containers:
        - name: redis-api-container # the container name in POD
          image: mast007/redisdemo:v1 # image name that will be pulled
          resources: # very important configuration for the POD so that service will be loaded and executed
            limits:
              cpu: "500m" # allocate half CPU for this service
              memory: "128Mi" # 128 MB of memory
          ports:
            - containerPort: 80            
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-api # the service app name
  name: redis-api-service # name for the service deployment
spec:
  ports:
    - port: 8080 # the port used to call service from external apps
      targetPort: 80 # the container port
  selector:
    app: redis-api-pod # the POD where the image will be deployed in container
  type: LoadBalancer # provides a public access to the service     